# Map github usernames to Socialcast usernames and assign review buddies
review_buddies:
  vanm:
    socialcast_username: VanMiranda
    buddy: wireframe
  wireframe:
    socialcast_username: RyanSonnek
    buddy: vanm

base_branch: master
staging_branch: staging
prototype_branch: prototype
