# Map github usernames to Socialcast usernames and assign review buddies
review_buddies:
  janesmith:
    socialcast_username: JaneSmith
    buddy: johndoe
  johndoe:
    socialcast_username: JohnDoe
    buddy: janesmith

specialty_reviewers:
  a:
    label: API
    command: (a)pi
    socialcast_username: JohnSmith
  s:
    label: Security
    command: (s)ecurity
    socialcast_username: KellyWilliams

base_branch: master
staging_branch: staging
prototype_branch: prototype

aggregate_branches:
  - prototype
  - staging

enforce_staging_before_release: true
